const TMDB_W500 = "https://image.tmdb.org/t/p/w500"

/** TMDB poster paths — fetched from trending/popular (films + series). */
const SPLASH_POSTER_PATHS = [
  "/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg",
  "/yihdXomYb5kTeSivtFndMy5iDmf.jpg",
  "/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg",
  "/lIsMeDbwntNXSUVHmWMMRXEZOVc.jpg",
  "/40I66L7QKguTFDPvcLcdiTbAD7I.jpg",
  "/tBtqTCimYm3DKck3t8A2mgJaKVK.jpg",
  "/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg",
  "/te3zACrsYkS2x3mkjG6htLqhMo4.jpg",
  "/xTI42pmsP5EDnvsNJPEDubwWBQO.jpg",
  "/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg",
  "/ul4dQcA68mtSx8J56N5gEcaCCtP.jpg",
  "/13ZcJzSGEqVgDSqsS9U5EkQwPkV.jpg",
  "/yPV87cvDabRMTZs6NIbZLOufBLR.jpg",
  "/mJS0IF7Af3WpPRhSTDT6rGpiLzw.jpg",
  "/vPVY3S57lEooBLJCg6KGdMHkUxm.jpg",
  "/eTp7gSPkSF3Aw79mNx1NkBP1PZT.jpg",
  "/6QtL9rl3Zb4d8qW6EJ4qO5hSSfU.jpg",
  "/1iaoDCWAM5C1kvlmIiCrLUE16uM.jpg",
  "/dQgIcW6Th08kMRf2HBoYWoFE6OD.jpg",
  "/lV8YHwGkYZsm6EfIqnhaSz2avKt.jpg",
  "/in1R2dDc421JxsoRWaIIAqVI2KE.jpg",
  "/gtoV2udbEnUgkMuCNX8zJrEwm7N.jpg",
  "/pRtJagIxpfODzzb0T0NAvZSzErC.jpg",
  "/5MrRCj7z92YLWMXHeWKp19eJPYv.jpg",
  "/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg",
  "/kru9Y5uRXdZFcUyeRlcv4bP4hOr.jpg",
  "/3t7xGceBAsSzWMuDdUpa6xS0x7p.jpg",
  "/aJrG7OkoTMPWG5c8opz8a93AZPY.jpg",
  "/NY7ZwSMw5PjoJdK2CObqiTj7Bm.jpg",
  "/jj7AYkz2OLRDL1wfJmjTXyWQ5I4.jpg",
  "/nO68XVx5of8hlBwEOGOkPC8Mveu.jpg",
  "/mX9tqfpjqwreONJHhap7SnSSowe.jpg",
  "/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg",
  "/hpKIZO05WwgAWQlv2VcpqZtg6ap.jpg",
  "/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg",
  "/rYLQbyIvbEd0lF84iXrx7CbPcBB.jpg",
  "/5MHtxPEfmN4b0rHzfEZRcm6v9WI.jpg",
  "/oftZNfyTVNU7IfOqoGLoT8MGvNs.jpg",
  "/jeSvTYUjRtV0xNjEupHpMgrBwsZ.jpg",
  "/c2jswCrMoqDEBEXwSAlrCWtXdfZ.jpg",
  "/8912AsVuS7Sj915apArUFbv6F9L.jpg",
  "/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg",
  "/gkHNa8q3RNhgj2EMuoYWJUHsMa6.jpg",
  "/pXENxAzOBrTSDJGxDcUnlNTNmWr.jpg",
  "/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg",
  "/7NrvUI3vnW8H3rD7ExKcTL7KRcQ.jpg",
  "/ybrX94xQm8lXYpZAPRmwD9iIbWP.jpg",
  "/iCvucorbs3hFqWshDbLe0fHzB71.jpg",
] as const

export const SPLASH_POSTER_URLS: string[] = SPLASH_POSTER_PATHS.map(
  (path) => `${TMDB_W500}${path}`,
)
